version: "3.8"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=news
      - POSTGRES_USER=lena
      - POSTGRES_PASSWORD=pass
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  redis:
    image: "redis:alpine"
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
  celery:
    build: .
    command: celery -A developstoday worker -l info
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
  celery-beat:
    build: .
    command: celery -A developstoday beat -l info
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
